### ISSUE TITLE
qrcode only appears on localhost

### ISSUE THREAD

**Issue by rafaWPP** [salman0ansari/whatsapp-api-nodejs#321]
qrcode only appears on localhost
does not appear in php requests from a server

``$curl = curl_init();

curl_setopt_array($curl, array(
  CURLOPT_URL => 'IPSERVER:21228/instance/qrbase64?key=123',
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => '',
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 0,
  CURLOPT_FOLLOWLOCATION => true,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => 'GET',
));

$response = curl_exec($curl);

curl_close($curl);
echo $response;``

return
``{"error":false,"message":"QR Base64 fetched successfully","qrcode":""}``

**Comment by sairmali** [comment]
send me your full code ...

**Comment by aelguezbari** [comment]
Same error i'm getting an empty string for qr base64

i'm using PHP on a différent server where whatsapp-api-nodejs is installed. on a browser it's works after i'm using the PHP code the qrcode become empty (event when re-using it on a browser)

**Comment by kiphe19** [comment]
Same error when calling via php using guzzlehttp

**Comment by gauravjethava1818** [comment]
The same error shows me from the last 5 days.
response get from online server
"error" => false
  "message" => "QR Base64 fetched successfully"
  "qrcode" => ""

**Comment by IhsanDevs** [comment]
Previously I also had this problem. Then I thought about adding a delay to the request. Because this API also takes a while to generate the QR Code. And this worked on my code. Give a 3-second delay on the request to get the QR Code after initializing the instance.

This is my code.

<details>
<summary>Init instance</summary>


```php
    public function initInstance()
    {
        $token = Str::random(32);

        $response = $this->client->request('GET', 'instance/init', [
            'query' => [
                'token' => $token,
            ],
        ]);
        $response = $response->getBody()->getContents();
        $response = json_decode($response);

        return $response;
    }
```
</details>

<details>
<summary>Get QR Code in base64</summary>


```php
    public function getBase64Qr($key)
    {
        sleep(3); // <-- Add delay for get QR Code
        $response = $this->client->request('GET', 'instance/qrbase64', [
            'query' => [
                'key' => $key,
            ],
        ]);
        $response = $response->getBody()->getContents();
        return json_decode($response);
    }
```
</details>


<details>
<summary>A Response</summary>

![screely-1666786598937](https://user-images.githubusercontent.com/66362682/198025482-63df9e46-8cc4-47d9-a3bf-29afbb62b28a.png)

</details>

It's work 👍🏼
